.PHONY: clean All

All:
	@echo "----------Building project:[ add1tonum - Debug ]----------"
	@cd "add1tonum" && "$(MAKE)" -f  "add1tonum.mk"
clean:
	@echo "----------Cleaning project:[ add1tonum - Debug ]----------"
	@cd "add1tonum" && "$(MAKE)" -f  "add1tonum.mk" clean
