.PHONY: clean All

All:
	@echo "----------Building project:[ queue_using_stack - Debug ]----------"
	@"$(MAKE)" -f  "queue_using_stack.mk"
clean:
	@echo "----------Cleaning project:[ queue_using_stack - Debug ]----------"
	@"$(MAKE)" -f  "queue_using_stack.mk" clean
