.PHONY: clean All

All:
	@echo "----------Building project:[ secondsmallest - Debug ]----------"
	@cd "secondsmallest" && "$(MAKE)" -f  "secondsmallest.mk"
clean:
	@echo "----------Cleaning project:[ secondsmallest - Debug ]----------"
	@cd "secondsmallest" && "$(MAKE)" -f  "secondsmallest.mk" clean
