.PHONY: clean All

All:
	@echo "----------Building project:[ zerosatend - Debug ]----------"
	@cd "zerosatend" && "$(MAKE)" -f  "zerosatend.mk"
clean:
	@echo "----------Cleaning project:[ zerosatend - Debug ]----------"
	@cd "zerosatend" && "$(MAKE)" -f  "zerosatend.mk" clean
