.PHONY: clean All

All:
	@echo "----------Building project:[ dfs - Debug ]----------"
	@"$(MAKE)" -f  "dfs.mk"
clean:
	@echo "----------Cleaning project:[ dfs - Debug ]----------"
	@"$(MAKE)" -f  "dfs.mk" clean
