.PHONY: clean All

All:
	@echo "----------Building project:[ firstlastswap - Debug ]----------"
	@cd "firstlastswap" && "$(MAKE)" -f  "firstlastswap.mk"
clean:
	@echo "----------Cleaning project:[ firstlastswap - Debug ]----------"
	@cd "firstlastswap" && "$(MAKE)" -f  "firstlastswap.mk" clean
