.PHONY: clean All

All:
	@echo "----------Building project:[ infixtopostfix - Debug ]----------"
	@cd "infixtopostfix" && "$(MAKE)" -f  "infixtopostfix.mk"
clean:
	@echo "----------Cleaning project:[ infixtopostfix - Debug ]----------"
	@cd "infixtopostfix" && "$(MAKE)" -f  "infixtopostfix.mk" clean
