.PHONY: clean All

All:
	@echo "----------Building project:[ tree_to_bst - Debug ]----------"
	@cd "tree_to_bst" && "$(MAKE)" -f  "tree_to_bst.mk"
clean:
	@echo "----------Cleaning project:[ tree_to_bst - Debug ]----------"
	@cd "tree_to_bst" && "$(MAKE)" -f  "tree_to_bst.mk" clean
