.PHONY: clean All

All:
	@echo "----------Building project:[ operations - Debug ]----------"
	@cd "operations" && "$(MAKE)" -f  "operations.mk"
clean:
	@echo "----------Cleaning project:[ operations - Debug ]----------"
	@cd "operations" && "$(MAKE)" -f  "operations.mk" clean
