.PHONY: clean All

All:
	@echo "----------Building project:[ stackusingsinglequeue - Debug ]----------"
	@cd "stackusingsinglequeue" && "$(MAKE)" -f  "stackusingsinglequeue.mk"
clean:
	@echo "----------Cleaning project:[ stackusingsinglequeue - Debug ]----------"
	@cd "stackusingsinglequeue" && "$(MAKE)" -f  "stackusingsinglequeue.mk" clean
